from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi2(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 565)
        MainWindow.setMinimumSize(QtCore.QSize(339, 565))
        MainWindow.setMaximumSize(QtCore.QSize(339, 565))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 1))
        MainWindow.setToolTipDuration(-1)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 531))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_buttons = QtWidgets.QFrame(self.frame)
        self.frame_buttons.setGeometry(QtCore.QRect(10, 120, 321, 421))
        self.frame_buttons.setStyleSheet("")
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.point = QtWidgets.QPushButton(self.frame_buttons)
        self.point.setGeometry(QtCore.QRect(140, 350, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.point.setFont(font)
        self.point.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.point.setObjectName("point")
        self.three = QtWidgets.QPushButton(self.frame_buttons)
        self.three.setGeometry(QtCore.QRect(140, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.three.setFont(font)
        self.three.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.three.setObjectName("three")
        self.zero = QtWidgets.QPushButton(self.frame_buttons)
        self.zero.setGeometry(QtCore.QRect(70, 350, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.zero.setFont(font)
        self.zero.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.zero.setObjectName("zero")
        self.two = QtWidgets.QPushButton(self.frame_buttons)
        self.two.setGeometry(QtCore.QRect(70, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.two.setFont(font)
        self.two.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);;border-radius: 30px;")
        self.two.setObjectName("two")
        self.eight = QtWidgets.QPushButton(self.frame_buttons)
        self.eight.setGeometry(QtCore.QRect(70, 140, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eight.setFont(font)
        self.eight.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.eight.setObjectName("eight")
        self.back = QtWidgets.QPushButton(self.frame_buttons)
        self.back.setGeometry(QtCore.QRect(210, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);\n"
"border-radius: 30px;")
        self.back.setObjectName("back")
        self.five = QtWidgets.QPushButton(self.frame_buttons)
        self.five.setGeometry(QtCore.QRect(70, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.five.setFont(font)
        self.five.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.five.setObjectName("five")
        self.seven = QtWidgets.QPushButton(self.frame_buttons)
        self.seven.setGeometry(QtCore.QRect(0, 140, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.seven.setFont(font)
        self.seven.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 30px;")
        self.seven.setObjectName("seven")
        self.plus_minus = QtWidgets.QPushButton(self.frame_buttons)
        self.plus_minus.setGeometry(QtCore.QRect(0, 350, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plus_minus.setFont(font)
        self.plus_minus.setStyleSheet("border-radius: 30px;color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);")
        self.plus_minus.setObjectName("plus_minus")
        self.multiply = QtWidgets.QPushButton(self.frame_buttons)
        self.multiply.setGeometry(QtCore.QRect(210, 140, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.multiply.setFont(font)
        self.multiply.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.multiply.setObjectName("multiply")
        self.x_square = QtWidgets.QPushButton(self.frame_buttons)
        self.x_square.setGeometry(QtCore.QRect(70, 70, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_square.setFont(font)
        self.x_square.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.x_square.setObjectName("x_square")
        self.divide = QtWidgets.QPushButton(self.frame_buttons)
        self.divide.setGeometry(QtCore.QRect(210, 70, 111, 61))
        self.divide.setMinimumSize(QtCore.QSize(111, 61))
        self.divide.setMaximumSize(QtCore.QSize(111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.divide.setFont(font)
        self.divide.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);\n"
"border-radius: 30px;")
        self.divide.setObjectName("divide")
        self.root = QtWidgets.QPushButton(self.frame_buttons)
        self.root.setGeometry(QtCore.QRect(140, 70, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.root.setFont(font)
        self.root.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.root.setObjectName("root")
        self.per = QtWidgets.QPushButton(self.frame_buttons)
        self.per.setGeometry(QtCore.QRect(0, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.per.setFont(font)
        self.per.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 30px;")
        self.per.setObjectName("per")
        self.six = QtWidgets.QPushButton(self.frame_buttons)
        self.six.setGeometry(QtCore.QRect(140, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.six.setFont(font)
        self.six.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.six.setObjectName("six")
        self.four = QtWidgets.QPushButton(self.frame_buttons)
        self.four.setGeometry(QtCore.QRect(0, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.four.setFont(font)
        self.four.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.four.setObjectName("four")
        self.plus = QtWidgets.QPushButton(self.frame_buttons)
        self.plus.setGeometry(QtCore.QRect(210, 280, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plus.setFont(font)
        self.plus.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.plus.setObjectName("plus")
        self.equal = QtWidgets.QPushButton(self.frame_buttons)
        self.equal.setGeometry(QtCore.QRect(210, 350, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.equal.setFont(font)
        self.equal.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.equal.setObjectName("equal")
        self.one_by_x = QtWidgets.QPushButton(self.frame_buttons)
        self.one_by_x.setGeometry(QtCore.QRect(0, 70, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.one_by_x.setFont(font)
        self.one_by_x.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 30px;")
        self.one_by_x.setObjectName("one_by_x")
        self.nine = QtWidgets.QPushButton(self.frame_buttons)
        self.nine.setGeometry(QtCore.QRect(140, 140, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nine.setFont(font)
        self.nine.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.nine.setObjectName("nine")
        self.minus = QtWidgets.QPushButton(self.frame_buttons)
        self.minus.setGeometry(QtCore.QRect(210, 210, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.minus.setFont(font)
        self.minus.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.minus.setObjectName("minus")
        self.one = QtWidgets.QPushButton(self.frame_buttons)
        self.one.setGeometry(QtCore.QRect(0, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.one.setFont(font)
        self.one.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.one.setObjectName("one")
        self.clear = QtWidgets.QPushButton(self.frame_buttons)
        self.clear.setGeometry(QtCore.QRect(140, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear.setFont(font)
        self.clear.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 30px;")
        self.clear.setObjectName("clear")
        self.ce = QtWidgets.QPushButton(self.frame_buttons)
        self.ce.setGeometry(QtCore.QRect(70, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ce.setFont(font)
        self.ce.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 30px;")
        self.ce.setObjectName("ce")
        self.frame_calculations_display = QtWidgets.QFrame(self.frame)
        self.frame_calculations_display.setGeometry(QtCore.QRect(10, 40, 321, 71))
        self.frame_calculations_display.setStyleSheet("")
        self.frame_calculations_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_calculations_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_calculations_display.setObjectName("frame_calculations_display")
        self.label_2 = QtWidgets.QLabel(self.frame_calculations_display)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_calculations_display)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 311, 20))
        self.label_3.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(117, 117, 117);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 339, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuThemes = QtWidgets.QMenu(self.menuSettings)
        self.menuThemes.setObjectName("menuThemes")
        MainWindow.setMenuBar(self.menuBar)
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")
        self.menuThemes.addAction(self.actionDark)
        self.menuThemes.addAction(self.actionLight)
        self.menuSettings.addAction(self.menuThemes.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.point.setText(_translate("MainWindow", "."))
        self.three.setText(_translate("MainWindow", "3"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.two.setText(_translate("MainWindow", "2"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.back.setToolTip(_translate("MainWindow", "Remove/Back"))
        self.back.setText(_translate("MainWindow", "<"))
        self.five.setText(_translate("MainWindow", "5"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.plus_minus.setText(_translate("MainWindow", "+/-"))
        self.multiply.setToolTip(_translate("MainWindow", "Multiply"))
        self.multiply.setText(_translate("MainWindow", "X"))
        self.x_square.setToolTip(_translate("MainWindow", "Square"))
        self.x_square.setText(_translate("MainWindow", "x²"))
        self.divide.setToolTip(_translate("MainWindow", "Divide"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.root.setToolTip(_translate("MainWindow", "Square root"))
        self.root.setText(_translate("MainWindow", "²√x"))
        self.per.setText(_translate("MainWindow", "%"))
        self.six.setText(_translate("MainWindow", "6"))
        self.four.setText(_translate("MainWindow", "4"))
        self.plus.setToolTip(_translate("MainWindow", "Plus"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.equal.setText(_translate("MainWindow", "="))
        self.one_by_x.setToolTip(_translate("MainWindow", "one by x"))
        self.one_by_x.setText(_translate("MainWindow", "1/x"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.minus.setToolTip(_translate("MainWindow", "Subtract"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.one.setText(_translate("MainWindow", "1"))
        self.clear.setToolTip(_translate("MainWindow", "Clear"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.ce.setToolTip(_translate("MainWindow", "Clear recent calculation"))
        self.ce.setText(_translate("MainWindow", "CE"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Standard"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuThemes.setTitle(_translate("MainWindow", "Themes"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionLight.setText(_translate("MainWindow", "Light"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi2(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
